### ISSUE TITLE
Normal Jumping also causes durability loss

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#31]
It seems the wings can't tell jumps from flaps. Wings lose durability much faster as a result.

**Comment by Tombenpotter** [comment]
Fixed in one of the commits. I can't remember which one though :P

**Comment by Shahelion** [comment]
Seems like this is still an issue, except now even the normal jumping is treated as a flap. For example, wearing cardboard wings, I can't even jump up one block in height now.

GIF for reference https://i.gyazo.com/f09dadc1dd291780beea08e7220acfad.mp4

Also I updated to the latest version, yet don't see any wings from Immersive Engineering. Were they just not added yet?
